name = "nw-proxy"
main = "index.js"
compatibility_date = "2023-10-30"

kv_namespaces = [
  { binding = "SESSIONS", id = "your_kv_namespace_id_here", preview_id = "your_kv_namespace_preview_id_here" }
]
